[pytest]
testpaths=tests
python_files = test_*.py
addopts = -v
markers =
    smoke: Smoke test suite
    regression: Regression test suite
    sanity: Sanity test suite
    login: Login test suite
    checkout: Checkout test suite
    inventory: Home test suite
    cart: Cart test suite