name: Allure Report

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Clean Allure Results
        run: |
          rm -rf allure-results
          rm -rf allure-report
          mkdir allure-results

      - name: Run Tests
        run: |
          pytest tests/test_login.py::TestLogin::test_login_with_valid_credentials -v --alluredir=allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Verify Report Files
        run: |
          echo "Contents of allure-history:"
          ls -R allure-history

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
